import { AiOutlineInstagram } from "react-icons/ai";
import { BsDot } from "react-icons/bs";


const ModalData = {
    Content: [
        {
            id: '1',
            mainVideo: './images/eight6.jpg',
            profilePic: './images/profile.jpg',
            profileName: 'Audrey Williamson',
            dotIcon: <BsDot />,
            instaIcon: <AiOutlineInstagram />,
            accountId: '@bluebear234',
            impressions: '124K',
            reach: '124K',
            likes: '12.4K',
            comments: '24',
            enRate: '12.5%',
            impressionsTitle: 'Impressions',
            reachTitle: 'Tot. reach',
            likesTitle: 'Tot. actions',
            engRateTitle: 'Engag. rate',
            descriptionTitle: 'Description',
            descriptionContent: 'There are many variations of passages of Lorem Ipsum available .There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available',
            mentionsTitle: 'Mentions',
            mentionsContent: '@Companyname',
            hashtagsTitle: 'Hashtags',
            hashtagsContent: '#compayname',
            locationTitle:'Location',
            locationContent: '2464 Valley View Ln undefined Coppell. Virginia 88719 United States',

        },
        {
            id: '2',
            mainVideo: './video/video1.mp4',
            profilePic: './images/profile-4.jpg',
            profileName: 'Donland Trupm',
            dotIcon: <BsDot />,
            instaIcon: <AiOutlineInstagram />,
            accountId: '@bluebear234',
            impressions: '124K',
            reach: '0',
            likes: '0',
            comments: '24',
            enRate: '12.5%',
            impressionsTitle: 'Impressions',
            reachTitle: 'Tot. reach',
            likesTitle: 'Tot. actions',
            engRateTitle: 'Engag. rate',
            descriptionTitle: 'Description',
            descriptionContent: 'There are many variations of passages of Lorem Ipsum available .There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available',
            mentionsTitle: 'Mentions',
            mentionsContent: '@Companyname',
            hashtagsTitle: 'Hashtags',
            hashtagsContent: '#compayname',
            locationTitle:'Location',
            locationContent: '2464 Valley View Ln undefined Coppell. Virginia 88719 United States',

        },
        {
            id: '3',
            mainVideo: './video/video2.mp4',
            profilePic: './images/eight5.jpg',
            profileName: 'Imran Khan',
            dotIcon: <BsDot />,
            instaIcon: <AiOutlineInstagram />,
            accountId: '@bluebear234',
            impressions: '124K',
            reach: '124K',
            likes: '12.4K',
            comments: '24',
            enRate: '12.5%',
            impressionsTitle: 'Impressions',
            reachTitle: 'Tot. reach',
            likesTitle: 'Tot. actions',
            engRateTitle: 'Engag. rate',
            descriptionTitle: 'Description',
            descriptionContent: 'There are many variations of passages of Lorem Ipsum available .There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available',
            mentionsTitle: 'Mentions',
            mentionsContent: '@Companyname',
            hashtagsTitle: 'Hashtags',
            hashtagsContent: '#compayname',
            locationTitle:'Location',
            locationContent: '2464 Valley View Ln undefined Coppell. Virginia 88719 United States',

        },
        {
            id: '4',
            mainVideo: './video/video3.mp4',
            profilePic: './images/eight6.jpg',
            profileName: 'Netlify',
            dotIcon: <BsDot />,
            instaIcon: <AiOutlineInstagram />,
            accountId: '@bluebear234',
            impressions: '124K',
            reach: '124K',
            likes: '12.4K',
            comments: '24',
            enRate: '12.5%',
            impressionsTitle: 'Impressions',
            reachTitle: 'Tot. reach',
            likesTitle: 'Tot. actions',
            engRateTitle: 'Engag. rate',
            descriptionTitle: 'Description',
            descriptionContent: 'There are many variations of passages of Lorem Ipsum available .There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available.There are many variations of passages of Lorem Ipsum available',
            mentionsTitle: 'Mentions',
            mentionsContent: '@Companyname',
            hashtagsTitle: 'Hashtags',
            hashtagsContent: '#compayname',
            locationTitle:'Location',
            locationContent: '2464 Valley View Ln undefined Coppell. Virginia 88719 United States',

        },
       
      
    ]
};

export default ModalData;